/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.fidentis.gui.actions.landmarks;

import cz.fidentis.featurepoints.FpModel;
import cz.fidentis.featurepoints.FpTexter;
import cz.fidentis.utils.SortUtils;
import java.awt.Component;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author xferkova
 */
public class PickTrainingLandmarkDialog extends JFrame {

    private LandmarkTrainDialogueTopComponent parent;
    
    /**
     * Creates new form PickTrainingLandmarkDialog
     */
    public PickTrainingLandmarkDialog(LandmarkTrainDialogueTopComponent parent, HashMap<Integer, Boolean> landmarksUsage) {
        initComponents();
        setInfo(parent, landmarksUsage);
    }
    
    private void setInfo(LandmarkTrainDialogueTopComponent parent, HashMap<Integer, Boolean> landmarksUsage){
        this.parent = parent;
        DefaultListModel active = new DefaultListModel();
        DefaultListModel inactive = new DefaultListModel();
        List<Integer> sortedIndices = SortUtils.instance().asSortedList(landmarksUsage.keySet());
        
        for(Integer i : sortedIndices){
            if(landmarksUsage.get(i))
                active.addElement(FpTexter.getInstance().getFPname(i));
            else
                inactive.addElement(FpTexter.getInstance().getFPname(i));
        }
        
        activeList.setModel(active);
        inactiveList.setModel(inactive);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveChoiceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        makeInactiveButton = new javax.swing.JButton();
        makeActiveButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        activeList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        inactiveList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(saveChoiceButton, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.saveChoiceButton.text")); // NOI18N
        saveChoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChoiceButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.jLabel2.text")); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(makeInactiveButton, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.makeInactiveButton.text")); // NOI18N
        makeInactiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeInactiveButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(makeActiveButton, org.openide.util.NbBundle.getMessage(PickTrainingLandmarkDialog.class, "PickTrainingLandmarkDialog.makeActiveButton.text")); // NOI18N
        makeActiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActiveButtonActionPerformed(evt);
            }
        });

        activeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(activeList);

        inactiveList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(inactiveList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(makeInactiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(makeActiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveChoiceButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(makeInactiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makeActiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(saveChoiceButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveChoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChoiceButtonActionPerformed
        HashMap<Integer, Boolean> newLandmarks = new HashMap<>();
        
        for(int i = 0; i < activeList.getModel().getSize(); i++){
            newLandmarks.put(FpTexter.getInstance().getTypeFromName(activeList.getModel().getElementAt(i)), Boolean.TRUE);
        }
        
        for(int i = 0; i < inactiveList.getModel().getSize(); i++){
            newLandmarks.put(FpTexter.getInstance().getTypeFromName(inactiveList.getModel().getElementAt(i)), Boolean.FALSE);
        }
        
        parent.setUsedLandmarks(newLandmarks);
        this.dispose();
    }//GEN-LAST:event_saveChoiceButtonActionPerformed

    private void makeInactiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeInactiveButtonActionPerformed
        List<String> selected = activeList.getSelectedValuesList();
        
        for(String lm : selected){
            ((DefaultListModel) activeList.getModel()).removeElement(lm);
            insert((DefaultListModel) inactiveList.getModel(), lm);
        }
       
    }//GEN-LAST:event_makeInactiveButtonActionPerformed

    private void makeActiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActiveButtonActionPerformed
        List<String> selected = inactiveList.getSelectedValuesList();
        
        for(String lm : selected){
            ((DefaultListModel) inactiveList.getModel()).removeElement(lm);
            insert((DefaultListModel) activeList.getModel(), lm);
        }
       
    }//GEN-LAST:event_makeActiveButtonActionPerformed

    private void insert(DefaultListModel model, String landmarkName){
        int index = FpTexter.getInstance().getTypeFromName(landmarkName);
        
        if(model.size() == 0 || index < FpTexter.getInstance().getTypeFromName((String)model.firstElement())){
            model.add(0, landmarkName);
            return;
        }
        
        for(int i = 0; i < model.getSize() - 1; i++){
            int above = FpTexter.getInstance().getTypeFromName((String)model.getElementAt(i));
            int below = FpTexter.getInstance().getTypeFromName((String)model.getElementAt(i+1));
            
            if(index > above && index < below){
                model.add(i+1, landmarkName);
                return;
            }         
        }
        
        model.addElement(landmarkName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> activeList;
    private javax.swing.JList<String> inactiveList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton makeActiveButton;
    private javax.swing.JButton makeInactiveButton;
    private javax.swing.JButton saveChoiceButton;
    // End of variables declaration//GEN-END:variables
}
