/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.fidentis.gui.featurepoints;

import cz.fidentis.gui.*;
import cz.fidentis.featurepoints.FacialPoint;
import com.jogamp.opengl.util.Animator;
import java.awt.Color;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLJPanel;
import java.util.Timer;

/**
 *
 * @author Katka
 */
public class FeaturePointsCanvas extends Canvas {

    /**
     * Creates new form Canvas
     */
    private ArrayList<ComparisonButton> buttons = new ArrayList<ComparisonButton>();

    public FeaturePointsCanvas(ProjectTopComponent tc) {
        super(tc);

        GLCapabilities capabilities = new GLCapabilities(GLProfile.get(GLProfile.GL2));
        capabilities.setDoubleBuffered(true);
        //    capabilities.setAlphaBits(0);
        glJPanel = new GLJPanel(capabilities);
        glAnimatorControl = new Animator(glJPanel);
        glAnimatorControl.start();
        initComponents();

        jPanel2.add(glJPanel);
        this.validate();
    }



    public void enableFPDescriptions(Boolean en) {
        featurePointsPanel.setVisible(en);
        textPane.setEnabled(!en);
        textPane.setVisible(!en);
    }
    
    
    public void enableFPMeasurements(Boolean en){
        textPane.setEnabled(en);
        textPane.setVisible(en);
        featurePointsPanel.setVisible(!en);
    }
    
    public void setPonitsLocationEditable(Boolean edit){
        xTextField.setEditable(edit);       
        yTextField.setEditable(edit);       
        zTextField.setEditable(edit);
        Color color= Color.white;
        if(edit){
            color= Color.LIGHT_GRAY;
        }
        zTextField.setBackground(color);
        xTextField.setBackground(color);
        yTextField.setBackground(color);
    }
    

    public void setDescriptionText(String text)
    {
        textPane.setText(text);
    }
    
    public void setInfo(FacialPoint fp){
        jLabel2.setText(fp.getName());
        xTextField.setText(Float.toString(fp.getPosition().x));
        yTextField.setText(Float.toString(fp.getPosition().y));
        zTextField.setText(Float.toString(fp.getPosition().z));
        jTextArea1.setText(fp.getInfo());
    }
    
    public void setCoordInfo(FacialPoint fp){
        xTextField.setText(Float.toString(fp.getPosition().x));
        yTextField.setText(Float.toString(fp.getPosition().y));
        zTextField.setText(Float.toString(fp.getPosition().z));        
    }
    
    public void resetInfo(){
        jLabel2.setText("-");
        xTextField.setText("-");
        yTextField.setText("-");
        zTextField.setText("-");
        jTextArea1.setText("-");
    }
    
    public void setFeaturePointsPanelVisibility(boolean bool){
        featurePointsPanel.setVisible(bool);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane = new javax.swing.JLayeredPane();
        rightNavigationButton = new javax.swing.JButton();
        upNavigationButton = new javax.swing.JButton();
        minusNavigationButton = new javax.swing.JButton();
        leftnavigationButton = new javax.swing.JButton();
        homeNavigationButton = new javax.swing.JButton();
        plusNavigationButton = new javax.swing.JButton();
        downNavigationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        featurePointsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zTextField = new javax.swing.JTextField();
        yTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textPane = new javax.swing.JTextPane();

        jLayeredPane.setMinimumSize(new java.awt.Dimension(300, 0));
        jLayeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLayeredPaneComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLayeredPaneComponentShown(evt);
            }
        });

        rightNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/right22.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(rightNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.rightNavigationButton.text")); // NOI18N
        rightNavigationButton.setBorder(null);
        rightNavigationButton.setBorderPainted(false);
        rightNavigationButton.setContentAreaFilled(false);
        rightNavigationButton.setFocusPainted(false);
        rightNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/right22pressed.png"))); // NOI18N
        rightNavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightNavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightNavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(rightNavigationButton);
        rightNavigationButton.setBounds(91, 60, 22, 22);
        jLayeredPane.setLayer(rightNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        upNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/up22.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(upNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.upNavigationButton.text")); // NOI18N
        upNavigationButton.setBorder(null);
        upNavigationButton.setContentAreaFilled(false);
        upNavigationButton.setFocusPainted(false);
        upNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/up22pressed.png"))); // NOI18N
        upNavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                upNavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                upNavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(upNavigationButton);
        upNavigationButton.setBounds(63, 32, 22, 22);
        jLayeredPane.setLayer(upNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        minusNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/minus.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(minusNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.minusNavigationButton.text")); // NOI18N
        minusNavigationButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minusNavigationButton.setBorderPainted(false);
        minusNavigationButton.setContentAreaFilled(false);
        minusNavigationButton.setFocusPainted(false);
        minusNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/minusPressed.png"))); // NOI18N
        minusNavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minusNavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minusNavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(minusNavigationButton);
        minusNavigationButton.setBounds(62, 150, 22, 22);
        jLayeredPane.setLayer(minusNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        leftnavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/left22.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(leftnavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.leftnavigationButton.text")); // NOI18N
        leftnavigationButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftnavigationButton.setContentAreaFilled(false);
        leftnavigationButton.setFocusPainted(false);
        leftnavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/left22pressed.png"))); // NOI18N
        leftnavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leftnavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                leftnavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(leftnavigationButton);
        leftnavigationButton.setBounds(33, 60, 22, 22);
        jLayeredPane.setLayer(leftnavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        homeNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/home22.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(homeNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.homeNavigationButton.text")); // NOI18N
        homeNavigationButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homeNavigationButton.setContentAreaFilled(false);
        homeNavigationButton.setFocusPainted(false);
        homeNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/home22pressed.png"))); // NOI18N
        homeNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeNavigationButtonActionPerformed(evt);
            }
        });
        jLayeredPane.add(homeNavigationButton);
        homeNavigationButton.setBounds(63, 60, 22, 22);
        jLayeredPane.setLayer(homeNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        plusNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/plus.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(plusNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.plusNavigationButton.text")); // NOI18N
        plusNavigationButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        plusNavigationButton.setBorderPainted(false);
        plusNavigationButton.setContentAreaFilled(false);
        plusNavigationButton.setFocusPainted(false);
        plusNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/plusPressed.png"))); // NOI18N
        plusNavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plusNavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plusNavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(plusNavigationButton);
        plusNavigationButton.setBounds(62, 126, 22, 22);
        jLayeredPane.setLayer(plusNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        downNavigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/down22.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(downNavigationButton, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.downNavigationButton.text")); // NOI18N
        downNavigationButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        downNavigationButton.setContentAreaFilled(false);
        downNavigationButton.setFocusPainted(false);
        downNavigationButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/down22pressed.png"))); // NOI18N
        downNavigationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                downNavigationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                downNavigationButtonMouseReleased(evt);
            }
        });
        jLayeredPane.add(downNavigationButton);
        downNavigationButton.setBounds(63, 90, 22, 22);
        jLayeredPane.setLayer(downNavigationButton, javax.swing.JLayeredPane.MODAL_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/fidentis/gui/resources/navigationBackground.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jLabel1.text")); // NOI18N
        jLayeredPane.add(jLabel1);
        jLabel1.setBounds(30, 30, 86, 86);
        jLayeredPane.setLayer(jLabel1, javax.swing.JLayeredPane.MODAL_LAYER);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jLayeredPane.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);
        jLayeredPane.setLayer(jPanel2, javax.swing.JLayeredPane.PALETTE_LAYER);
        jPanel2.setBounds(0, 0,jLayeredPane.getWidth(),jLayeredPane.getHeight());

        featurePointsPanel.setBackground(new java.awt.Color(255, 255, 255));
        featurePointsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.text")); // NOI18N
        jLabel2.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jLabel3.text")); // NOI18N

        xTextField.setEditable(false);
        xTextField.setBackground(new java.awt.Color(255, 255, 255));
        xTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        xTextField.setText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.xTextField.text")); // NOI18N
        xTextField.setBorder(null);
        xTextField.setPreferredSize(new java.awt.Dimension(12, 22));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jLabel6.text")); // NOI18N

        zTextField.setEditable(false);
        zTextField.setBackground(new java.awt.Color(255, 255, 255));
        zTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        zTextField.setText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.zTextField.text")); // NOI18N
        zTextField.setBorder(null);
        zTextField.setPreferredSize(new java.awt.Dimension(12, 22));

        yTextField.setEditable(false);
        yTextField.setBackground(new java.awt.Color(255, 255, 255));
        yTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        yTextField.setText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.yTextField.text")); // NOI18N
        yTextField.setBorder(null);
        yTextField.setPreferredSize(new java.awt.Dimension(12, 22));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jLabel5.text")); // NOI18N

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(4);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jTextArea1.text")); // NOI18N
        jTextArea1.setToolTipText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.jTextArea1.toolTipText")); // NOI18N
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout featurePointsPanelLayout = new javax.swing.GroupLayout(featurePointsPanel);
        featurePointsPanel.setLayout(featurePointsPanelLayout);
        featurePointsPanelLayout.setHorizontalGroup(
            featurePointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featurePointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(featurePointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(featurePointsPanelLayout.createSequentialGroup()
                        .addGroup(featurePointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(featurePointsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        featurePointsPanelLayout.setVerticalGroup(
            featurePointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featurePointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(featurePointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(zTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        jLayeredPane.add(featurePointsPanel);
        featurePointsPanel.setBounds(10, 170, 250, 120);
        jLayeredPane.setLayer(featurePointsPanel, javax.swing.JLayeredPane.POPUP_LAYER);
        featurePointsPanel.setVisible(false);

        textPane.setEditable(false);
        textPane.setBorder(null);
        textPane.setText(org.openide.util.NbBundle.getMessage(FeaturePointsCanvas.class, "FeaturePointsCanvas.textPane.text")); // NOI18N
        textPane.setEnabled(false);
        textPane.setPreferredSize(new java.awt.Dimension(300, 100));
        textPane.setVisible(false);
        jLayeredPane.add(textPane);
        textPane.setBounds(10, 180, 250, 110);
        jLayeredPane.setLayer(textPane, javax.swing.JLayeredPane.POPUP_LAYER);

        add(jLayeredPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void homeNavigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeNavigationButtonActionPerformed
        listener.rotationAndSizeRestart();
        if (listener2 != null) {
            listener2.rotationAndSizeRestart();
        }
    }//GEN-LAST:event_homeNavigationButtonActionPerformed

    private void jLayeredPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLayeredPaneComponentResized
        jPanel2.setBounds(0, 0, jLayeredPane.getWidth(), jLayeredPane.getHeight());
        glJPanel.setBounds(jLayeredPane.getX(), jLayeredPane.getY(), jLayeredPane.getWidth(), jLayeredPane.getHeight());

        textPane.setLocation(10, jLayeredPane.getHeight() - textPane.getHeight() - 10);
        featurePointsPanel.setLocation(10, jLayeredPane.getHeight() - textPane.getHeight() - 10);


    }//GEN-LAST:event_jLayeredPaneComponentResized

    private void jLayeredPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLayeredPaneComponentShown
        jPanel2.setBounds(0, 0, jLayeredPane.getWidth(), jLayeredPane.getHeight());
        glJPanel.setBounds(jLayeredPane.getX(), jLayeredPane.getY(), jLayeredPane.getWidth(), jLayeredPane.getHeight());

        textPane.setLocation(10, jLayeredPane.getHeight() - textPane.getHeight() - 10);
        featurePointsPanel.setLocation(10, jLayeredPane.getHeight() - textPane.getHeight() - 10);


    }//GEN-LAST:event_jLayeredPaneComponentShown

 

    private void leftnavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftnavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.rotateLeft(2);
                if (listener2 != null) {
                    listener2.rotateLeft(2);
                }
            }
        };
        timer.schedule(task, 500, 100);
    }//GEN-LAST:event_leftnavigationButtonMousePressed


    
    
    private void upNavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upNavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.rotateUp(2);
                if (listener2 != null) {
                    listener2.rotateUp(2);
                }
            }
        };
        timer.schedule(task, 500, 100);

    }//GEN-LAST:event_upNavigationButtonMousePressed

    private void upNavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upNavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.rotateUp(22.5);
            if (listener2 != null) {
                listener2.rotateUp(22.5);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_upNavigationButtonMouseReleased

    private void rightNavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightNavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.rotateRight(2);
                if (listener2 != null) {
                    listener2.rotateRight(2);
                }
            }
        };
        timer.schedule(task, 500, 100);
    }//GEN-LAST:event_rightNavigationButtonMousePressed

    private void rightNavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightNavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.rotateRight(22.5);
            if (listener2 != null) {
                listener2.rotateRight(22.5);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_rightNavigationButtonMouseReleased

    private void leftnavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftnavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.rotateLeft(22.5);
            if (listener2 != null) {
                listener2.rotateLeft(22.5);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_leftnavigationButtonMouseReleased

    private void downNavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downNavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.rotateDown(2);
                if (listener2 != null) {
                    listener2.rotateDown(2);
                }
            }
        };
        timer.schedule(task, 500, 100);
    }//GEN-LAST:event_downNavigationButtonMousePressed

    private void downNavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downNavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.rotateDown(22.5);
            if (listener2 != null) {
                listener2.rotateDown(22.5);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_downNavigationButtonMouseReleased

    private void plusNavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusNavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.zoomIn(3);
                if (listener2 != null) {
                    listener2.zoomIn(3);
                }
            }
        };
        timer.schedule(task, 500, 100);
    }//GEN-LAST:event_plusNavigationButtonMousePressed

    private void plusNavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusNavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.zoomIn(30);
            if (listener2 != null) {
                listener2.zoomIn(30);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_plusNavigationButtonMouseReleased

    private void minusNavigationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusNavigationButtonMousePressed
        timer = new Timer();
        startClickTime = System.currentTimeMillis();
        task = new TimerTask() {
            @Override
            public void run() {
                listener.zoomOut(3);
                if (listener2 != null) {
                    listener2.zoomOut(3);
                }
            }
        };
        timer.schedule(task, 500, 100);
    }//GEN-LAST:event_minusNavigationButtonMousePressed

    private void minusNavigationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusNavigationButtonMouseReleased
        timer.cancel();
        if ((System.currentTimeMillis() - startClickTime) < 500) {
            listener.zoomOut(30);
            if (listener2 != null) {
                listener2.zoomOut(30);
            }
        }
        startClickTime = 0;
    }//GEN-LAST:event_minusNavigationButtonMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton downNavigationButton;
    private javax.swing.JPanel featurePointsPanel;
    private javax.swing.JButton homeNavigationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton leftnavigationButton;
    private javax.swing.JButton minusNavigationButton;
    private javax.swing.JButton plusNavigationButton;
    private javax.swing.JButton rightNavigationButton;
    private javax.swing.JTextPane textPane;
    private javax.swing.JButton upNavigationButton;
    private javax.swing.JTextField xTextField;
    private javax.swing.JTextField yTextField;
    private javax.swing.JTextField zTextField;
    // End of variables declaration//GEN-END:variables
}
